# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages (Configurator)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: HTML/CSS/JS Minifier
        # You may pin to the exact commit or the version.
        # uses: devatherock/minify-js@a25175eaf2c438680b21b73882d4837418e9d58b
        uses: devatherock/minify-js@v1.0.3
        with:
          # File to minify or a folder containing files to minify. By default, all files in current folder and its subfolders will be minified
          directory: './Source/loaderConfigurator/src' # optional
          # Path where the minified files will be saved. By default, the minified files will be saved in the original file path
          output: './Source/loaderConfigurator/dist' # optional
          # Indicates if the output files should have the suffix '.min' added after the name. Default is true
          add_suffix: false # optional
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './Source/loaderConfigurator/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
